FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    libreoffice \
    bash \
    curl \
    net-tools \
    iputils-ping \
    vim \
    nano

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ .

EXPOSE 8501

CMD [ "streamlit", "run", "main.py", "--server.address=0.0.0.0" ]